# Generated by Django 2.1.7 on 2019-04-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cartitem_order'),
        ('api', '0002_cart'),
        ('api', '0002_profile'),
    ]

    operations = [
    ]
